import type { Behavior } from './types'

export const behaviors: Behavior[] = [
  {
    id: 'agree',
    label: '"Agree?" at the end of posts',
    emoji: '🤝',
    points: 8,
    classTags: ['Engagement Farmer', 'Reply Guy'],
  },
  {
    id: 'humble-brag',
    label: 'Humble-bragging about offers/salary',
    emoji: '💰',
    points: 12,
    classTags: ['Humble Bragger', 'Hustle Bro'],
  },
  {
    id: 'story-post',
    label: 'Writing 20-line story posts',
    emoji: '📖',
    points: 10,
    classTags: ['Corporate Poet', 'Inspirational Liar'],
  },
  {
    id: 'selfie',
    label: 'Posting selfies as "professional content"',
    emoji: '🤳',
    points: 15,
    classTags: ['Selfie CEO', 'Engagement Farmer'],
  },
  {
    id: 'fired-post',
    label: '"I was fired and it was the best thing"',
    emoji: '🔥',
    points: 14,
    classTags: ['Inspirational Liar', 'Humble Bragger'],
  },
  {
    id: 'thought-leader',
    label: 'Calling yourself a "thought leader"',
    emoji: '🧠',
    points: 18,
    classTags: ['Thought Leader', 'Hustle Bro'],
  },
  {
    id: 'emoji-bullets',
    label: 'Using emoji bullet points in every post',
    emoji: '✅',
    points: 7,
    classTags: ['Engagement Farmer', 'Corporate Poet'],
  },
  {
    id: 'hustle-grind',
    label: '"Rise and grind" / 5AM club posts',
    emoji: '⏰',
    points: 11,
    classTags: ['Hustle Bro', 'Inspirational Liar'],
  },
  {
    id: 'grief-leverage',
    label: 'Using personal tragedy for engagement',
    emoji: '😢',
    points: 20,
    classTags: ['Grief Exploiter', 'Engagement Farmer'],
  },
  {
    id: 'recruiter-dm',
    label: '"Just had an AMAZING call with a candidate"',
    emoji: '📞',
    points: 9,
    classTags: ['Recruiter Cringe', 'Humble Bragger'],
  },
  {
    id: 'reply-every',
    label: 'Replying to every LinkedIn influencer',
    emoji: '💬',
    points: 6,
    classTags: ['Reply Guy', 'Engagement Farmer'],
  },
  {
    id: 'airport-selfie',
    label: 'Airport/conference selfies',
    emoji: '✈️',
    points: 13,
    classTags: ['Selfie CEO', 'Humble Bragger'],
  },
  {
    id: 'fake-poll',
    label: 'Posting engagement-bait polls',
    emoji: '📊',
    points: 8,
    classTags: ['Engagement Farmer', 'Reply Guy'],
  },
  {
    id: 'life-hack',
    label: 'Sharing obvious advice as "life-changing"',
    emoji: '💡',
    points: 10,
    classTags: ['Thought Leader', 'Inspirational Liar'],
  },
  {
    id: 'hashtag-overload',
    label: '10+ hashtags on every post',
    emoji: '#️⃣',
    points: 7,
    classTags: ['Engagement Farmer', 'Generic Professional'],
  },
  {
    id: 'crying-post',
    label: '"I\'m not crying, you\'re crying" posts',
    emoji: '😭',
    points: 12,
    classTags: ['Grief Exploiter', 'Corporate Poet'],
  },
  {
    id: 'linkedin-is-not',
    label: '"LinkedIn is NOT Facebook" (on LinkedIn)',
    emoji: '🙄',
    points: 9,
    classTags: ['Reply Guy', 'Generic Professional'],
  },
  {
    id: 'fake-convo',
    label: '"A CEO once told me..." (fictional conversation)',
    emoji: '🎭',
    points: 16,
    classTags: ['Inspirational Liar', 'Thought Leader'],
  },
  {
    id: 'reject-offer',
    label: '"I rejected a $500K offer because culture"',
    emoji: '🚫',
    points: 17,
    classTags: ['Humble Bragger', 'Hustle Bro'],
  },
  {
    id: 'connection-spam',
    label: 'Mass-connecting then pitching in DMs',
    emoji: '📨',
    points: 11,
    classTags: ['Recruiter Cringe', 'Engagement Farmer'],
  },
]
